[package]
name = "dylib-dep"
version = "0.1.0"
edition = "2021"
authors = []
publish = false

[lib]
name = "dylib_dep"
crate-type = ["cdylib", "rlib"]
[patch.crates-io]
gimli = { git = "https://github.com/jyn514/gimli", branch = "shared-attrs", version = "0.31.1" }
