[package]
name = "debuglink"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = { path = "../.." }
[patch.crates-io]
gimli = { git = "https://github.com/jyn514/gimli", branch = "shared-attrs", version = "0.31.1" }
